# Generated by Django 5.1.1 on 2024-09-07 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_app_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
