# Generated by Django 5.1.1 on 2024-09-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='current_version',
            new_name='version',
        ),
    ]
