# Generated by Django 5.1.1 on 2024-09-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_coment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish_date',
            new_name='publish_datetime',
        ),
    ]
