# Generated by Django 5.1.1 on 2024-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_publish_date_comment_publish_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
